# Generated by Django 4.2.27 on 2026-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmaevent',
            name='event_type',
            field=models.CharField(choices=[('POST_LIKED', 'Post Liked'), ('COMMENT_LIKED', 'Comment Liked'), ('POST_UNLIKED', 'Post Unliked'), ('COMMENT_UNLIKED', 'Comment Unliked')], max_length=20),
        ),
    ]
